# Generated by Django 5.2.10 on 2026-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
