# Generated by Django 5.2.10 on 2026-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('m_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('prof_img', models.ImageField(upload_to='images/')),
                ('phone_no', models.CharField(max_length=13)),
            ],
        ),
    ]
