# Generated by Django 5.2.10 on 2026-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
