# Generated by Django 5.2.13 on 2026-05-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expensescategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forExpenses', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incomecategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forIncome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpensesAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ExpensesDescription', models.TextField(blank=True, null=True)),
                ('ExpensesDate', models.DateField()),
                ('ExpensesCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExpenseApp.expensescategories')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncomeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IncomeDescription', models.TextField(blank=True, null=True)),
                ('IncomeDate', models.DateField()),
                ('IncomeCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExpenseApp.incomecategories')),
            ],
        ),
    ]
